# Generated by Django 3.0 on 2021-02-25 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Aperette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('recette', models.BooleanField(default=False)),
                ('proportions', models.IntegerField()),
                ('alcoolAssocie', models.CharField(default='', max_length=100)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aperetteAPI.Categorie')),
                ('ingredients', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aperetteAPI.Ingredient')),
            ],
        ),
    ]
