# Generated by Django 3.0 on 2021-02-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aperetteAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aperette',
            name='categories',
        ),
        migrations.AddField(
            model_name='aperette',
            name='categories',
            field=models.ManyToManyField(to='aperetteAPI.Categorie'),
        ),
        migrations.RemoveField(
            model_name='aperette',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='aperette',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, to='aperetteAPI.Ingredient'),
        ),
    ]
